test_that("modelData Binary", {
    expect_no_error({modelData(cadmium1, type = "binary")})
    expect_no_error({modelData(cadmium2, type = "binary")})
    expect_no_error({modelData(chlordan, type = "binary")})
    expect_no_error({modelData(copper, type = "binary")})
    expect_no_error({modelData(dichromate, type = "binary")})
    expect_no_error({modelData(propiconazole, type = "binary")})
    expect_no_error({modelData(zinc, type = "binary")})
})

test_that("modelData Count", {
    expect_no_error({modelData(cadmium1, type = "count")})
    expect_no_error({modelData(cadmium2, type = "count")})
    expect_no_error({modelData(chlordan, type = "count")})
    expect_no_error({modelData(copper, type = "count")})
    expect_no_error({modelData(zinc, type = "count")})
})

test_that("modelData_Continuous", {
    expect_no_error({modelData(cadmium_daphnia, type = "continuous")})
    expect_no_error({modelData(copper_daphnia, type = "continuous")})
    expect_no_error({modelData(zinc_daphnia, type = "continuous")})
    expect_no_error({modelData(subst01_lymnaea, type = "continuous")})
    expect_no_error({modelData(plant01, type = "continuous")})
    expect_no_error({modelData(plant02, type = "continuous")})
    expect_no_error({modelData(plant03, type = "continuous")})
    expect_no_error({modelData(plant04, type = "continuous")})
    expect_no_error({modelData(plant05, type = "continuous")})
    expect_no_error({modelData(plant06, type = "continuous")})
    expect_no_error({modelData(plant07, type = "continuous")})
    expect_no_error({modelData(plant08, type = "continuous")})
    expect_no_error({modelData(plant09, type = "continuous")})
    expect_no_error({modelData(plant10, type = "continuous")})
})
